// Generated by the e2e-perfromance-test-suite-k6 skill.
// SmartBuy has no auth (guest checkout only, per CLAUDE.md) -- just a base
// URL and JSON headers, no cookie jar / bearer token helpers needed.

const BASE_URL = __ENV.BASE_URL || 'http://127.0.0.1:8833';

export function apiUrl(path) {
  return `${BASE_URL}${path}`;
}

export function jsonHeaders() {
  return { headers: { 'Content-Type': 'application/json' } };
}
