// Generated by the e2e-perfromance-test-suite-k6 skill.
// Builds k6 `options` (scenarios + thresholds) from the five NFR values the
// skill always asks the user for (see references/nfr-requirements.md) --
// passed in as -e flags at `k6 run` time, never hardcoded here. This is
// what keeps the test scripts themselves repeatable across runs with
// different NFR targets: the scripts don't change, only the env does.
//
// Required -e vars (SKILL.md always supplies all of these):
//   BASE_URL            e.g. http://127.0.0.1:8833
//   CONCURRENT_USERS    integer -- drives the constant-vus session scenario
//   TPS_TARGET          integer req/s -- sustained-throughput plateau
//   PEAK_LOAD           integer req/s -- burst ceiling, >= TPS_TARGET
//   LATENCY_P95_MS      integer -- per-request p95 threshold
//   TAT_P95_MS          integer -- full-transaction p95 threshold
// Optional -e vars (sane defaults if omitted -- fine for a first dry run,
// but SKILL.md should still surface them so the user can override):
//   RAMP_UP (default '1m'), HOLD (default '3m'), PEAK_HOLD (default '30s'),
//   RAMP_DOWN (default '30s'), SESSION_DURATION (default '5m')

export function buildOptions() {
  const concurrentUsers = requireNumber('CONCURRENT_USERS');
  const tpsTarget = requireNumber('TPS_TARGET');
  const peakLoad = requireNumber('PEAK_LOAD');
  const latencyP95Ms = requireNumber('LATENCY_P95_MS');
  const tatP95Ms = requireNumber('TAT_P95_MS');

  const rampUp = __ENV.RAMP_UP || '1m';
  const hold = __ENV.HOLD || '3m';
  const peakHold = __ENV.PEAK_HOLD || '30s';
  const rampDown = __ENV.RAMP_DOWN || '30s';
  const sessionDuration = __ENV.SESSION_DURATION || '5m';

  if (peakLoad < tpsTarget) {
    throw new Error(`PEAK_LOAD (${peakLoad}) must be >= TPS_TARGET (${tpsTarget})`);
  }

  const arrivalCapacity = Math.max(concurrentUsers, peakLoad);

  return {
    scenarios: {
      // Answers "what happens with N real sessions active" -- TAT is
      // measured here. See references/k6-conventions.md for why this is
      // kept separate from the throughput scenario below.
      concurrent_sessions: {
        executor: 'constant-vus',
        vus: concurrentUsers,
        duration: sessionDuration,
        exec: 'orderLifecycle',
        tags: { scenario: 'concurrent_sessions' },
      },
      // Answers "can you sustain N requests/sec, and survive a burst to
      // Peak Load" -- arrival-rate holds throughput constant instead of
      // silently degrading it under latency (see k6-conventions.md).
      throughput_ramp: {
        executor: 'ramping-arrival-rate',
        startRate: 0,
        timeUnit: '1s',
        preAllocatedVUs: arrivalCapacity * 2,
        maxVUs: arrivalCapacity * 4,
        stages: [
          { target: tpsTarget, duration: rampUp },
          { target: tpsTarget, duration: hold },
          { target: peakLoad, duration: peakHold },
          { target: 0, duration: rampDown },
        ],
        exec: 'browseProducts',
        tags: { scenario: 'throughput_ramp' },
      },
    },
    thresholds: {
      http_req_duration: [`p(95)<${latencyP95Ms}`],
      http_req_failed: ['rate<0.01'],
      checks: ['rate>0.99'],
      order_lifecycle_tat_ms: [`p(95)<${tatP95Ms}`],
      'group_duration{group:::order_lifecycle}': [`p(95)<${tatP95Ms}`],
      // Always-true threshold expressions used purely to force k6 to emit
      // scenario-scoped submetrics in --summary-export -- without this,
      // http_reqs in the summary blends both scenarios' request volume
      // into one average that can't be compared to TPS_TARGET/PEAK_LOAD
      // meaningfully. See nfr-report.mjs.
      'http_reqs{scenario:throughput_ramp}': ['count>=0'],
    },
  };
}

function requireNumber(envVar) {
  const raw = __ENV[envVar];
  if (raw === undefined || raw === '') {
    throw new Error(
      `Missing -e ${envVar}=<value>. This skill always asks the user for all five NFR ` +
        'targets before running -- see references/nfr-requirements.md. Never run with a guessed default.',
    );
  }
  const value = Number(raw);
  if (Number.isNaN(value)) {
    throw new Error(`-e ${envVar}="${raw}" is not a number.`);
  }
  return value;
}
