// Canonical product catalog. server/seed.js loads this into Postgres;
// the frontend uses CATEGORIES for filter UI (product data itself comes from the API).
export const CATEGORIES = [
  'Electronics',
  'Fashion',
  'Home & Kitchen',
  'Books',
  'Sports & Outdoors',
  'Beauty & Personal Care',
];

const p = (
  id,
  name,
  category,
  price,
  emoji,
  color,
  description,
  rating,
  stock
) => ({ id, name, category, price, emoji, color, description, rating, stock });

export const PRODUCTS = [
  p(1, 'Wireless Noise-Cancelling Headphones', 'Electronics', 129.99, '🎧', '#4f46e5',
    'Over-ear Bluetooth headphones with active noise cancellation and 30-hour battery life.', 4.6, 24),
  p(2, 'Smart Fitness Watch', 'Electronics', 89.5, '⌚', '#0891b2',
    'Track heart rate, sleep, and workouts with a 7-day battery and AMOLED display.', 4.3, 41),
  p(3, 'Portable Bluetooth Speaker', 'Electronics', 39.99, '🔊', '#dc2626',
    'Compact waterproof speaker with rich bass and 12-hour playtime.', 4.4, 60),
  p(4, '4K Action Camera', 'Electronics', 149.0, '📷', '#059669',
    'Capture stunning 4K video with waterproof housing and image stabilization.', 4.1, 15),
  p(5, 'Mechanical Keyboard', 'Electronics', 74.99, '⌨️', '#7c3aed',
    'RGB backlit mechanical keyboard with hot-swappable switches.', 4.7, 33),
  p(6, 'USB-C Fast Charger 65W', 'Electronics', 24.99, '🔌', '#ea580c',
    'Compact GaN charger that fast-charges laptops, tablets, and phones.', 4.5, 80),
  p(7, "Men's Classic Denim Jacket", 'Fashion', 59.99, '🧥', '#1d4ed8',
    'Timeless denim jacket with a comfortable regular fit.', 4.2, 28),
  p(8, "Women's Running Shoes", 'Fashion', 79.99, '👟', '#db2777',
    'Lightweight breathable running shoes with responsive cushioning.', 4.6, 37),
  p(9, 'Unisex Wool Beanie', 'Fashion', 14.99, '🧢', '#65a30d',
    'Soft knit beanie to keep you warm through winter.', 4.3, 90),
  p(10, 'Leather Crossbody Bag', 'Fashion', 64.5, '👜', '#a16207',
    'Genuine leather crossbody bag with adjustable strap.', 4.4, 22),
  p(11, 'Polarized Sunglasses', 'Fashion', 29.99, '🕶️', '#334155',
    'UV400 polarized lenses with a durable lightweight frame.', 4.0, 55),
  p(12, "Men's Slim Fit Chinos", 'Fashion', 44.99, '👖', '#0f766e',
    'Comfortable stretch-fit chinos for everyday wear.', 4.1, 48),
  p(13, '12-Piece Non-Stick Cookware Set', 'Home & Kitchen', 119.99, '🍳', '#b91c1c',
    'Durable non-stick pots and pans set, dishwasher safe.', 4.5, 18),
  p(14, 'Programmable Coffee Maker', 'Home & Kitchen', 49.99, '☕', '#92400e',
    'Brew up to 12 cups with a 24-hour programmable timer.', 4.3, 26),
  p(15, 'Robot Vacuum Cleaner', 'Home & Kitchen', 189.0, '🤖', '#4338ca',
    'Smart mapping robot vacuum with app control and auto-recharge.', 4.4, 12),
  p(16, 'Memory Foam Pillow Set (2-Pack)', 'Home & Kitchen', 34.99, '🛏️', '#0d9488',
    'Ergonomic memory foam pillows for better neck support.', 4.6, 44),
  p(17, 'Stainless Steel Knife Set', 'Home & Kitchen', 69.99, '🔪', '#525252',
    '6-piece precision-forged knife set with wooden block.', 4.5, 30),
  p(18, 'Air Fryer 5.5L', 'Home & Kitchen', 84.99, '🍟', '#c2410c',
    'Oil-free air fryer with 8 preset cooking modes.', 4.7, 20),
  p(19, 'Atomic Habits', 'Books', 16.99, '📘', '#1e3a8a',
    'A practical guide to building good habits and breaking bad ones.', 4.8, 100),
  p(20, 'The Midnight Library', 'Books', 13.5, '📖', '#7c2d12',
    'A novel about the choices that go into a life well lived.', 4.6, 75),
  p(21, 'Sapiens: A Brief History of Humankind', 'Books', 18.99, '📗', '#166534',
    'A sweeping narrative of the history of the human species.', 4.7, 64),
  p(22, "Beginner's Guide to Cooking", 'Books', 21.0, '📙', '#9a3412',
    'Step-by-step recipes and techniques for new home cooks.', 4.2, 38),
  p(23, 'Yoga Mat with Carry Strap', 'Sports & Outdoors', 27.99, '🧘', '#7e22ce',
    'Extra-thick non-slip yoga mat, eco-friendly TPE material.', 4.5, 52),
  p(24, 'Adjustable Dumbbell Set', 'Sports & Outdoors', 159.0, '🏋️', '#334155',
    'Space-saving adjustable dumbbells from 5 to 52.5 lbs.', 4.6, 14),
  p(25, '2-Person Camping Tent', 'Sports & Outdoors', 89.99, '⛺', '#166534',
    'Weatherproof lightweight tent, easy 5-minute setup.', 4.3, 19),
  p(26, 'Insulated Water Bottle 32oz', 'Sports & Outdoors', 22.99, '🚰', '#0284c7',
    'Keeps drinks cold for 24 hours or hot for 12 hours.', 4.7, 88),
  p(27, 'Resistance Bands Set', 'Sports & Outdoors', 19.99, '💪', '#be123c',
    '5 resistance levels for strength and mobility training.', 4.4, 70),
  p(28, 'Vitamin C Serum', 'Beauty & Personal Care', 18.5, '🧴', '#f59e0b',
    'Brightening antioxidant serum for radiant, even-toned skin.', 4.5, 66),
  p(29, 'Electric Toothbrush', 'Beauty & Personal Care', 34.99, '🪥', '#0ea5e9',
    'Sonic electric toothbrush with 3 cleaning modes and timer.', 4.4, 40),
  p(30, 'Hair Dryer with Diffuser', 'Beauty & Personal Care', 42.0, '💇', '#e11d48',
    'Ionic hair dryer that reduces frizz and cuts drying time.', 4.3, 25),
];
