// Generated by the e2e-perfromance-test-suite-k6 skill.
// The real NFR run -- composes both scenarios under the options built from
// this run's five NFR targets (see ../lib/scenarios.js and
// references/nfr-requirements.md). Run with:
//
//   k6 run --summary-export=../reports/summary-<timestamp>.json \
//     -e BASE_URL=... -e CONCURRENT_USERS=... -e TPS_TARGET=... \
//     -e PEAK_LOAD=... -e LATENCY_P95_MS=... -e TAT_P95_MS=... \
//     tests/load-test.js
//
// Always run tests/smoke.js first (see references/k6-conventions.md).
import { buildOptions } from '../lib/scenarios.js';
import { orderLifecycle } from './order-lifecycle.js';
import { browseProducts } from './browse-products.js';

export const options = buildOptions();

export { orderLifecycle, browseProducts };
