// Generated by the e2e-perfromance-test-suite-k6 skill.
// Always run this before the full NFR profile (see
// references/k6-conventions.md's "Warm-up before the real run"). 1 VU, a
// couple of iterations of each flow, fails fast on a wrong port or a
// scenario-code bug -- in seconds, not minutes.
import { orderLifecycle } from './order-lifecycle.js';
import { browseProducts } from './browse-products.js';

export const options = {
  scenarios: {
    smoke_sessions: { executor: 'shared-iterations', vus: 1, iterations: 2, exec: 'orderLifecycle' },
    smoke_throughput: { executor: 'shared-iterations', vus: 1, iterations: 2, exec: 'browseProducts' },
  },
  thresholds: {
    http_req_failed: ['rate<0.5'], // loose -- this is a wiring check, not an NFR gate
  },
};

export { orderLifecycle, browseProducts };
